name: Build Windows Release

on:
  push:
    branches:
      - master

concurrency:
  group: build-windows
  cancel-in-progress: true

defaults:
  run:
    shell: powershell

env:
  CC: clang
  CXX: clang++
  CMAKE_VERSION: "4.1.2"
  VCPKG_CACHE_KEY: "vcpkg6"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:

      - name: Checkout
        run: |
          git clone --depth 1 "https://x-access-token:${{ secrets.RUIN_TOKEN }}@github.com/zhengkai/ruin.git" .
          echo "LOCALAPPDATA=$env:LOCALAPPDATA" >> $env:GITHUB_ENV
          echo "APPDATA=$env:APPDATA" >> $env:GITHUB_ENV

      - name: Cache CMake ${{ env.CMAKE_VERSION }}
        id: cache-cmake
        uses: actions/cache@v4
        with:
          path: cmake-portable
          key: cmake-${{ env.CMAKE_VERSION }}

      - name: Download CMake ${{ env.CMAKE_VERSION }}
        if: steps.cache-cmake.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://github.com/Kitware/CMake/releases/download/v$env:CMAKE_VERSION/cmake-$env:CMAKE_VERSION-windows-x86_64.zip" -OutFile cmake.zip
          Expand-Archive cmake.zip -DestinationPath cmake-portable
          Remove-Item cmake.zip

      - name: Save CMake Cache
        if: steps.cache-cmake.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: cmake-portable
          key: cmake-${{ env.CMAKE_VERSION }}

      - name: Add CMake to PATH
        run: |
          $dir = Get-ChildItem -Directory "cmake-portable" | Select-Object -First 1
          $cmakeBin = Join-Path $dir.FullName "bin"
          echo "$cmakeBin" >> "$env:GITHUB_PATH"
          & "$cmakeBin/cmake.exe" --version

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: |
            tool/vcpkg
            vcpkg_installed
            ${{ env.LOCALAPPDATA }}\vcpkg\archives
            ${{ env.APPDATA }}\vcpkg\archives
          key: ${{ env.VCPKG_CACHE_KEY }}-${{ hashFiles('vcpkg.json') }}

      - name: Clone vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: |
          $commit = jq -r '.[\"builtin-baseline\"]' vcpkg.json
          cd tool
          git init vcpkg
          cd vcpkg
          git remote add origin https://github.com/microsoft/vcpkg.git
          git fetch --depth 1 origin $commit
          git checkout $commit
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install --triplet x64-windows

      - name: CMake Configure
        run: |
          mkdir -p build
          cmake -B build -DCMAKE_TOOLCHAIN_FILE="$PWD\tool\vcpkg\scripts\buildsystems\vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
          Remove-Item -Recurse -Force .\tool\vcpkg\.git -ErrorAction SilentlyContinue

      - name: CMake Build
        run: |
          cmake --build build --config Release -- /m

      - name: Save vcpkg Cache
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            tool/vcpkg
            vcpkg_installed
            ${{ env.LOCALAPPDATA }}\vcpkg\archives
            ${{ env.APPDATA }}\vcpkg\archives
          key: ${{ env.VCPKG_CACHE_KEY }}-${{ hashFiles('vcpkg.json') }}

      - name: Download asset
        run: |
          git clone --depth 1 "https://github.com/zhengkai/ruin-asset.git" asset
          node misc\asset\copy.mjs

      - name: Try run
        run: |
          cd build\Release
          .\ruin.exe --version

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ruin-windows
          path: build\Release\*

      - name: Delete old daily tag
        run: |
          try { git tag -d daily } catch {}
          try { git push origin :refs/tags/daily } catch {}

      - name: Recreate daily tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag daily
          git push origin daily --force

      - name: Zip build output
        run: |
          cd build\Release
          7z a ..\..\ruin-win.zip .\*

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: daily
          name: Daily Build
          prerelease: true
          body: "Latest daily build."
          files: ruin-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.RUIN_TOKEN }}
